# Generated by Django 2.2.14 on 2022-03-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='dvr',
            field=models.CharField(blank=True, choices=[('86400', '1 день'), ('3d', '3 дня'), ('5d', '5 дней'), ('7d', '1 неделя'), ('14d', '2 недели')], max_length=10, verbose_name='Тип доступа'),
        ),
    ]
