# Generated by Django 2.2.14 on 2022-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220316_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='dvr',
            field=models.CharField(blank=True, choices=[('86400', '1 день'), ('259200', '3 дня'), ('432000', '5 дней'), ('604800', '1 неделя'), ('1209600', '2 недели')], max_length=10, verbose_name='Тип доступа'),
        ),
    ]
