# Generated by Django 2.2.14 on 2022-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220316_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='ip_addr',
            field=models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP Адресс сервера'),
        ),
    ]
